version: '3'

services:
  web:
    build: .
    volumes:
      - /usr/src/app/
      - static_volume:/usr/src/web/
    expose:
      - 8000
    env_file:
      - ./.env
    depends_on:
      - db
  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=django_app
      - POSTGRES_PASSWORD=django_app
      - POSTGRES_DB=django_app
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
    volumes:
      - static_volume:/usr/src/web/
volumes:
  postgres_data:
  static_volume:
