# Generated by Django 3.1.3 on 2020-11-03 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borough',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
