# Generated by Django 3.1.3 on 2020-11-10 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201103_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='price',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
